name: github-openai

on:
  push:
    branches:
      - main

jobs:
  openai:
    runs-on: ubuntu-latest
    steps:
    - name: wget github-openai binary v0.2.0
      run: |
        wget https://github.com/michalswi/github-openai/releases/download/v0.2.0/github-openai_linux_amd64
        chmod +x github-openai_linux_amd64
    - name: run github-openai
      env:
        API_KEY: ${{ secrets.API_KEY }}
        GITHUB_PAT: ${{ secrets.GH_PAT }}
        REPO_OWNER: ${{ github.repository_owner }}
        REPO_NAME: ${{ github.repository }}
      run: |
        REPO_NAME=$(echo $REPO_NAME | cut -d '/' -f 2)
        # export BRANCH_NAME=develop
        ./github-openai_linux_amd64
